name: Update latest projects

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Blog Post Workflow
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "LATEST_REPOS"
          feed_list: "https://rsshub.app/github/repos/apoorvdarshan"
          max_post_count: 3
          custom_tags: "<li><a href='{{url}}'>{{title}}</a></li>"
