name: Update latest repos in README

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch latest repos and update README
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: apoorvdarshan/apoorvdarshan
          event-type: update-readme
          client-payload: '{"date": "2025-05-18T23:56:55Z"}'
